### ISSUE TITLE
Invalid example in the doc

### ISSUE THREAD

**Issue by roosephu** [ruuda/rcl#30]
Here is the example taken from https://docs.ruuda.nl/rcl/functions/#first-class-functions:
```
let replicants = [
  { activation_year = 2016, name = "Pris Stratton" },
  { activation_year = 2016, name = "Roy Batty" },
  { activation_year = 2017, name = "Leon Kowalski" },
];
replicants.group_by(r => r.activation_year)
// Evaluates to:
{
  2016 = [
    { activation_year = 2016, name = "Pris Stratton" },
    { activation_year = 2016, name = "Roy Batty" },
  ],
  2017 = [
    { activation_year = 2017, name = "Leon Kowalski" },
  ],
}
```

However, `2016` and `2017` are not identifiers, thus they can't be used in record form.

**Comment by ruuda** [comment]
Good catch, that should be `:` instead of `=`. Thank you for reporting this. This is fixed in 20e61dd628ec447a1c6d1cb816777cb6adabca77, and updated now on the website.
