### ISSUE TITLE
Require escaping right curly brackets in f-strings

### ISSUE THREAD

**Issue by chloekek** [ruuda/rcl#44]
Currently you can only and have to only escape left curly brackets in f-strings. But this is ugly:

```rcl
f"""
tcp-request content reject if \{ dst 0.0.0.0 }
"""
```

Right curly brackets should also be required to escape, or at least allowed to:

```rcl
f"""
tcp-request content reject if \{ dst 0.0.0.0 \}
"""
```

**Comment by ruuda** [comment]
Makes sense to at least allow `\}`, fixed in 0f35dfe9d47cfd1cdac8b75404d1e651cc43debb.
