### ISSUE TITLE
Fail to compile on Windows

### ISSUE THREAD

**Issue by chutuananh2k** [ruuda/rcl#69]
here is the log:

> ''' cargo build                
>    Compiling unicode-width v0.1.11
>    Compiling rcl v0.5.0 (C:\source\rcl)                                                                                                                                                                                 
> warning: unexpected `cfg` condition name: `fuzzing`                                                                                                                                                                     
>   --> src\eval.rs:86:15
>    |
> 86 |         #[cfg(fuzzing)]
>    |               ^^^^^^^
>    |
>    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_
> cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
>    = help: consider using a Cargo feature instead
>    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>             [lints.rust]
>             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
>    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
>    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
>    = note: `#[warn(unexpected_cfgs)]` on by default
> 
> warning: unexpected `cfg` condition name: `fuzzing`
>   --> src\eval.rs:89:23
>    |
> 89 |         #[cfg(all(not(fuzzing), debug_assertions))]
>    |                       ^^^^^^^
>    |
>    = help: consider using a Cargo feature instead
>    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>             [lints.rust]
>             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
>    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
>    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> warning: unexpected `cfg` condition name: `fuzzing`
>   --> src\eval.rs:92:23
>    |
> 92 |         #[cfg(all(not(fuzzing), not(debug_assertions)))]
>    |                       ^^^^^^^
>    |
>    = help: consider using a Cargo feature instead
>    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>             [lints.rust]
>             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
>    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
>    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> warning: unexpected `cfg` condition name: `fuzzing`
>   --> src\stdlib.rs:83:11
>    |
> 83 |     #[cfg(fuzzing)]
>    |           ^^^^^^^
>    |
>    = help: consider using a Cargo feature instead
>    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>             [lints.rust]
>             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
>    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
>    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> warning: unexpected `cfg` condition name: `fuzzing`
>   --> src\stdlib.rs:85:15
>    |
> 85 |     #[cfg(not(fuzzing))]
>    |               ^^^^^^^
>    |
>    = help: consider using a Cargo feature instead
>    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>             [lints.rust]
>             unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
>    = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(fuzzing)");` to the top of the `build.rs`
>    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
> 
> warning: `rcl` (lib) generated 5 warnings                                                                                                                                                                               
> error[E0599]: no method named `write_depfile` found for struct `Loader` in the current scope                                                                                                                            
>    --> src/main.rs:297:33
>     |
> 297 |                     self.loader.write_depfile(&output, depfile_path)?;
>     |                                 ^^^^^^^^^^^^^ method not found in `Loader`
> 
> error[E0599]: no method named `write_depfile` found for struct `Loader` in the current scope
>    --> src/main.rs:335:33
>     |
> 335 |                     self.loader.write_depfile(&output, depfile_path)?;
>     |                                 ^^^^^^^^^^^^^ method not found in `Loader`
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `rcl` (bin "rcl") due to 2 previous errors
> '''

**Comment by ruuda** [comment]
Thank you for taking the time to open an issue. I pushed a temporary “fix” in 6c001ec to `master`. It means depfile support will not work on non-Unix systems for now, but at least compilation should work. Could you verify this?

Also, when pasting compiler output on GitHub, it’s helpful to wrap it [in a <code>```</code> code block](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to keep the output readable.

**Comment by ruuda** [comment]
I’m going to assume this is fixed, version 0.6.0 is released now. Feel free to comment if you still experience compilation problems.
